# Generated by Django 2.2.6 on 2019-12-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                ("meal_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=246)),
                ("calories_summary", models.FloatField()),
                ("price_summary", models.FloatField()),
                ("fat_summary", models.FloatField()),
                ("protein_summary", models.FloatField()),
                ("carbohydrates_summary", models.FloatField()),
                ("cellulose_summary", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "sex",
                    models.CharField(
                        choices=[("w", "woman"), ("m", "man"), ("\\N", "no data")],
                        max_length=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.FloatField()),
                (
                    "meal_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="BoxDiet.Meal"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="BoxDiet.User"
                    ),
                ),
            ],
        ),
    ]
