# Generated by Django 2.2.6 on 2019-12-09 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoxDiet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='rank',
            old_name='user_id',
            new_name='user',
        ),
    ]
