# Generated by Django 2.2.6 on 2019-12-09 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BoxDiet", "0002_auto_20191209_2116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="meal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals_user",
                to="BoxDiet.Meal",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meals_user",
                to="BoxDiet.User",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(
                choices=[("w", "kobieta "), ("m", "mężczyzna"), ("\\N", "brak danych")],
                max_length=5,
            ),
        ),
    ]
