# Generated by Django 2.2.6 on 2019-12-10 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoxDiet', '0004_auto_20191210_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reccomended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_mark', models.FloatField(null=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='BoxDiet.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended', to='BoxDiet.User')),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
