# Generated by Django 2.2.6 on 2019-12-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoxDiet', '0008_auto_20191210_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('w', 'Kobieta '), ('m', 'Mężczyzna'), ('\\N', 'Brak danych')], max_length=5, verbose_name='Płeć'),
        ),
    ]
