# Generated by Django 2.2.6 on 2020-03-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('BoxDiet', '0010_auto_20191215_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories_summary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbohydrates_summary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='cellulose_summary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fat_summary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='price_summary',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein_summary',
            field=models.FloatField(null=True),
        ),
    ]
